INSERT INTO TEST_TABLE VALUES(1, 'testData', 154, 'ShouldBeAllSmallCase', 45, 'Some long string In All Case TYPES', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- INSERT INTO URI_CACHE (URI, ACTION_TYPE, RESPONSE_DATA_ID) VALUES('/hello.json', 'GET', 1);